### ISSUE TITLE
HelpMainPage doesn't translate

### ISSUE THREAD

**Issue by eson57** [PawelSpoon/harbour-sailkick#7]
well... not into Swedish anyway. The rest of this app translates nicely.

**Comment by PawelSpoon** [comment]
you are the first who actually did translate the help page. maybe i need to change the source string, as it is html. will investigate it.over weekend

**Comment by eson57** [comment]
ok, I'll buy some popcorn.  ;)

**Comment by PawelSpoon** [comment]
i had a quick look on the file and it uses qsTr(), i am running my version in german and the first thin line below SailKick (top right of help page) gets translated.
i guess the reason is the long string itself, that is used as key is multi-line with some special chars and html tags. maybe it helps to change the source in qml and ts file to 'helptext' ?`
but if i do that how would you know what to translate ?

**Comment by eson57** [comment]
Well, I'm no good at this, as I'm still slowly learning programming, but my first thought was to look at how other developers do this. Maybe you can take a look at [Framrekkari](https://github.com/Buschtrommel/Framrekkari) for example? There's also a long helptext.

**Comment by PawelSpoon** [comment]
the reason were missing \ in the multiline resource string.
i have fixed that, the german help page translates now nicely to 'nothing' ;-)
i have uploaded the new source file to transifex too and i have copied your 'old' helptext translation into the new source string. can you please review it ?
Thanks a lot !
I have also uploaded the new version into openrepos. 
Cany you try it out ? it is version 1.52
i do not have yet an about page, so no place to add you to. but i will do that soon !
Cheers

**Comment by eson57** [comment]
Yes, help page is now translated, but settings page is not. The text below username is in english. I don't really remember if it was translated before your fix, but I think so.
I also think there is a few line breaks missing in help text. It should look more nicely if there was line breaks before Plans, Concerts and Settings don't you think?

**Comment by PawelSpoon** [comment]
i did change only helptext, so i assume that settings text was also broken. i will change it over weekend

**Comment by PawelSpoon** [comment]
the mentioned settings page text, was not using qsTr(). it was never translated. i have uploaded a new file in transifex.

**Comment by eson57** [comment]
Ok, translation done.

**Comment by PawelSpoon** [comment]
i have uploaded new version into open repos. plese verify the settings page.
regarding spaces: you are right, but i do not want to change it now. as it would require that all languages have again one untranslated string.
feel free to add the spaces into your translation 
Thanks !

**Comment by eson57** [comment]
Can't make it work at all now. Settings and help page are both untranslated. I updated and downloaded the translation at Transifex and made a clean reinstall of Sailkick 1.5-4 from OpenRepos, but settings and help  translations don't work.

**Comment by PawelSpoon** [comment]
pretty strange, cause i did translate the german help text to 'help text' and that was visible .
can you Switch your language to german ? and check if you see a Translation ?
i will recheck on phone

**Comment by eson57** [comment]
Yes, German help translation is ok. So is settings, except there's no line breaks. Guess there's something wrong with Swedish translation file then...

**Comment by PawelSpoon** [comment]
funny just tried german on my phone, is englisch ;-)
i will recheck, but give me some time

**Comment by eson57** [comment]
Of course, take your time.

**Comment by PawelSpoon** [comment]
tested with 1.5-5: german and swedish do work
finally

**Comment by eson57** [comment]
Great! Looking good to.  :)
